# Created by an LLM.
# Edited by me: image versions, grafana x-frame-options.

# Development Docker Compose
# Run infrastructure services in containers
# Run Go services and React app locally with `just` for hot-reload

# Note: version field omitted as per latest Docker Compose standards

networks:
  dev-network:
    driver: bridge

volumes:
  postgres-dev-data:
  grafana-dev-data:
  rabbitmq-dev-data:
  prometheus-dev-data:

services:
  # Database
  postgres:
    image: postgres:17.6
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  # Message broker
  rabbitmq:
    image: rabbitmq:4.1.3
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - dev-network
    volumes:
      - rabbitmq-dev-data:/var/lib/rabbitmq

  # Monitoring and observability
  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
      - "--web.enable-admin-api"
    volumes:
      - ./deploy/prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-dev-data:/prometheus
    networks:
      - dev-network

  grafana:
    image: grafana/grafana:11.5
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      # NOTE Only for local development.
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_X_FRAME_OPTIONS=allowall
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-dev-data:/var/lib/grafana
    networks:
      - dev-network
    depends_on:
      - prometheus

  # Optional containerized Go services (use scripts/with_build.sh)
  # Uncomment when you want to run services in containers instead of locally

  # api:
  #   build:
  #     context: .
  #     dockerfile: build.Dockerfile
  #     target: dev
  #   command: ["./scripts/run_service.sh", "api"]
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - PSQL_ADDR=postgres
  #     - PSQL_PORT=5432
  #     - PSQL_USER=user
  #     - PSQL_PASS=pass
  #     - PSQL_DB=db
  #     - PSQL_MAX_CONNS=10
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - dev-network
  #   volumes:
  #     - .:/workspace:cached
  #     - /workspace/target  # Anonymous volume for build artifacts

  # worker:
  #   build:
  #     context: .
  #     dockerfile: build.Dockerfile
  #     target: dev
  #   command: ["./scripts/run_service.sh", "worker"]
  #   environment:
  #     - PSQL_ADDR=postgres
  #     - PSQL_PORT=5432
  #     - PSQL_USER=user
  #     - PSQL_PASS=pass
  #     - PSQL_DB=db
  #     - PSQL_MAX_CONNS=10
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - dev-network
  #   volumes:
  #     - .:/workspace:cached
  #     - /workspace/target

  # aggregator:
  #   build:
  #     context: .
  #     dockerfile: build.Dockerfile
  #     target: dev
  #   command: ["./scripts/run_service.sh", "aggregator"]
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - PSQL_ADDR=postgres
  #     - PSQL_PORT=5432
  #     - PSQL_USER=user
  #     - PSQL_PASS=pass
  #     - PSQL_DB=db
  #     - PSQL_MAX_CONNS=10
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - dev-network
  #   volumes:
  #     - .:/workspace:cached
  #     - /workspace/target

  # streamer:
  #   build:
  #     context: .
  #     dockerfile: build.Dockerfile
  #     target: dev
  #   command: ["./scripts/run_service.sh", "streamer"]
  #   ports:
  #     - "8084:8084"
  #   environment:
  #     - PSQL_ADDR=postgres
  #     - PSQL_PORT=5432
  #     - PSQL_USER=user
  #     - PSQL_PASS=pass
  #     - PSQL_DB=db
  #     - PSQL_MAX_CONNS=10
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - dev-network
  #   volumes:
  #     - .:/workspace:cached
  #     - /workspace/target
