# Created by an LLM.

# Prometheus configuration for local development
# Use when running Go services locally with `just`
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
